### PR TITLE
feat: add rtd_cid for Reddit campaign tracking/attribution

### PR DESCRIPTION
**Pull request by aboscardin**
### Summary

This PR adds support for the Reddit click ID `rdt_cid` used in Reddit Ads, to the campaign parser and tracker, so that both `initial_rtd_cid` and `rtd_cid` are set as user attributes by the Marketing SDK. This will enable us (and others) to properly attribute traffic and conversion from Reddit ads and project ad spend. 

Reddit ads tracking documentation: https://redditinc.force.com/helpcenter/s/article/Set-up-third-party-measurement

### Checklist

* [x] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-TypeScript/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:  np

### CODE REVIEW

**Comment by aboscardin** [comment]
Hello 👋 - any feedback on this PR? We could really use the same level of support for Reddit click IDs as other attribution events in our campaigns. Thank you!

**Comment by kevinpagtakhan** [comment]
I'd be happy to bundle these changes with https://github.com/amplitude/Amplitude-TypeScript/pull/380 in a new version

**Review by kevinpagtakhan — APPROVED** [review]

**Comment by aboscardin** [comment]
Thanks @kevinpagtakhan!

**Comment by kevinpagtakhan** [comment]
Hey @aboscardin, `rtd_cid` tracking is available in @amplitude/analytics-browser@1.10.3

**Pull request merged**
