### PR TITLE
chore: rip marketing analytics sdk

### PR DESCRIPTION
**Pull request by kevinpagtakhan**
### Summary

Farewell to marketing analytics SDK

**Why?**
Browser SDK 2.0 now contains features that used to be unique to marketing analytics SDK.

**How can we support Marketing Analytics SDK?**
All v1.x versions of all packages in this repo are in a separate branch: https://github.com/amplitude/Amplitude-TypeScript/tree/v1.x and have its own github action for publishing.

### Checklist

* [x] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-TypeScript/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:  No

### CODE REVIEW

**Review by kelsonpw — APPROVED** [review]

**Comment by yuhao900914** [comment]
Is there any plan to describe this change in the doc center?

**Review by paladin8 — APPROVED** [review]
🎉

**Review by yuhao900914 — APPROVED** [review]

**Review by qingzhuozhen — APPROVED** [review]

**Review by justin-fiedler — APPROVED** [review]

**Comment by ondrej** [comment]
Kevin, are you actually saying goodbye to the SDK and putting it in maintenance mode, or just moving it to a separate branch and stopping automatic builds? If it's more of the former, do we need to do these:

* Update our docs to reflect this — e.g. move Marketing Analytics SDK under the Maintenance SDKs section and update https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/migration/#comparison
* Update our GTM template so they don't rely on no longer supported SDKs?

Hoping we can make it clear to folks externally what the status is of the Marketing Analytics SDK and the things that depend on it

**Comment by kevinpagtakhan** [comment]
> Kevin, are you actually saying goodbye to the SDK and putting it in maintenance mode, or just moving it to a separate branch and stopping automatic builds? If it's more of the former, do we need to do these:
> 
> * Update our docs to reflect this — e.g. move Marketing Analytics SDK under the Maintenance SDKs section and update https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/migration/#comparison
> * Update our GTM template so they don't rely on no longer supported SDKs?
> 
> Hoping we can make it clear to folks externally what the status is of the Marketing Analytics SDK and the things that depend on it

Not saying goodbye totally 😅 We have 1.x available and will be supported the same way as all other 1.x packages in this repo. Those packages have their own "main" branch which is "v1.x", while "main" branch contains all 2.x packages, where node and react-native SDK are private packages since they are not ready to be published. I'm removing the package from "main" branch since we do not foresee a version 2.x of marketing analytics, as that is what Browser SDK 2.x is. In addition, it helps clean up the plugin interface (some types are required only by marketing analytics) and optimize builds. None of the changes here are expected to surface publicly. We still offer marketing analytics 1.x the same way and are able add features and fixes as needed.

**Review by yuhao900914 — COMMENTED** [review]
Since you said RN and Node are private packages. Before we are publishing those 2 packages, how do we publish the fixes?

**Comment by kevinpagtakhan** [comment]
> Since you said RN and Node are private packages for now. Before we are publishing those 2 packages, how do we publish the fixes?

We have two branches, `v1.x` and `main` for v2.x. node and react-native are only private in `main` because those have 2.x versions in package.json. they are public on `v1.x`.

**Comment by kevinpagtakhan** [comment]
* main (or v2.x) https://github.com/amplitude/Amplitude-TypeScript/tree/main
* v1.x https://github.com/amplitude/Amplitude-TypeScript/tree/v1.x

it helps to view them as two different repos (in a single repo). they now have their own lineages, and we can support both the exact same way.

**Review by yuhao900914 — COMMENTED** [review]
Got it. Could we also document that somewhere, probably in the readme for each branch for notifying the engineers or who might not know about this conversation?

**Comment by kevinpagtakhan** [comment]
> Got it. Could we also document that somewhere, probably in the readme for each branch for notifying the engineers or who might not know about this conversation?

Sure, and it will be on CONTRIBUTING.md but would just take time. I just recently wrapped up features and fixes and working on dev docs now.

**Pull request merged**
