### PR TITLE
refactor: create separate package for common code for browser/react n…

### PR DESCRIPTION
**Pull request by kevinpagtakhan**
…ative sdk

### Summary

Moves all common code shared by browser and react native packages to browser-utils package.

### Checklist

* [x] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-TypeScript/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:  No

### CODE REVIEW

**Review by AlecBoutin — APPROVED** [review]

**Review by bgiori — APPROVED** [review]
-1219 !!!!

Awesome!

Only question is package name for me. I would consider some of the functionality in the new shared package to be more than just utility. 

maybe name it `analytics-browser-common` or `analytics-client-common`?

**Review by dnshi — APPROVED** [review]

**Comment by kevinpagtakhan** [comment]
@bgiori @dnshi @AlecBoutin I pushed another commit to include **all** other files that are shared between browser and react native code. I understand that the PR is huge however, but with no change to the behavior of the SDK, I feel confident that build and test would catch if anything was wrong with this PR.

**Comment by kevinpagtakhan** [comment]
@bgiori im open to changing the package name. I've reached out to the rest of the team to ask what they think

**Comment by kevinpagtakhan** [comment]
Change new package name to `analytics-client-common`

**Pull request merged**
