### PR TITLE
feat: landing page improvement

### PR DESCRIPTION
**Pull request by yuhao900914**
### Summary

https://amplitude.atlassian.net/browse/AMP-93561

Add a pageCount in the DET page view for analyzing the landing page and bounce rate.

- Reset the pageCount to 0 at the beginning of the session.
- Increment the pageCount with each page view during a session.
- 
### Checklist

* [ ] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-TypeScript/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:

### CODE REVIEW

**Review by izaaz — APPROVED** [review]

**Review by justin-fiedler — APPROVED** [review]

**Review by Mercy811 — APPROVED** [review]
Thanks Alyssa. 🙏 `pageCounter` is stored in cookie storage. LGTM.

**Review by qingzhuozhen — APPROVED** [review]
Change seems good, not sure if the naming needs more alignment later.

**Comment by yuhao900914** [comment]
It should be `pageCounter`! Thanks for reviewing!

**Comment by izaaz** [comment]
Actually thinking about this, do we have to prefix this with [Amplitude] to indicate this is an amplitude computed property? @yuhao900914

**Comment by yuhao900914** [comment]
@izaaz  Then that could be `[Amplitude] Page Counter` which aligned with other properties in page view event. Let me confirm with @Michelle Lee

**Comment by yuhao900914** [comment]
Update the property to `[Amplitude] Page Counter`.

**Pull request merged**
