### PR TITLE
fix(session-replay-browser): handle exceptions when creating an events manager

### PR DESCRIPTION
**Pull request by junjie-amplitude**
### Summary

A Jenkins error was reported in https://amplitude.atlassian.net/browse/AMP-108769. It was caused by the unhandled idb open error. This PR handles it when creating the events managers. The events manager creation fails when the [idb store creation](https://amplitude.sourcegraph.com/github.com/amplitude/Amplitude-TypeScript@v1.x/-/blob/packages/session-replay-browser/src/events/events-idb-store.ts?L95) fails, and it skips adding the events manager so no replays will be captured then.

### Checklist

* [ ] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-TypeScript/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:

### CODE REVIEW

**Review by jxiwang — APPROVED** [review]
LGTM

**Review by jackson-amplitude — APPROVED** [review]
Do we know when this happens?

**Comment by junjie-amplitude** [comment]
> Do we know when this happens?

@jackson-amplitude For example, when there is no enough disk space to open a new idb store.

**Comment by jackson-amplitude** [comment]
> > Do we know when this happens?
> 
> @jackson-amplitude For example, when there is no enough disk space to open a new idb store.

our storage footprint should be small. maybe worth a quick check to see if idb has any diagnostics that we can log (don't spend too much time though).

**Comment by junjie-amplitude** [comment]
> https://amplitude.atlassian.net/browse/AMP-108769

@jackson-amplitude Out of disk space is one of the possible reasons. Other reasons could be opening idb in incompatible browsers or simply an idb bug. People usually report this issue with no other diagnostic information. The solutions are often to restart the browser or so. So I think catching and logging the error in the console is the best we can do for it.

**Pull request merged**
