### PR TITLE
build: fix the CDN for marketing analytics browser GTM

### PR DESCRIPTION
**Pull request by yuhao900914**
### Checklist

* [ ] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-TypeScript/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:

### CODE REVIEW

**Comment by justin-fiedler** [comment]
@yuhao900914 from @kevinpagtakhan comment yesterday, should we also update [this part](https://github.com/amplitude/Amplitude-TypeScript/blob/cbf268ffa158d450aab8e501b6ceefc29aa0ac4b/packages/marketing-analytics-browser/generated/amplitude-gtm-snippet.js#L91) to include the following?
```
if (!window.amplitude) {
  window.amplitude = window.amplitudeGTM;
}
```

**Comment by yuhao900914** [comment]
> @yuhao900914 from @kevinpagtakhan comment yesterday, should we also update [this part](https://github.com/amplitude/Amplitude-TypeScript/blob/cbf268ffa158d450aab8e501b6ceefc29aa0ac4b/packages/marketing-analytics-browser/generated/amplitude-gtm-snippet.js#L91) to include the following?
> 
> ```
> if (!window.amplitude) {
>   window.amplitude = window.amplitudeGTM;
> }
> ```

Should this logic exist on amplitude-js-gtm side? 
https://github.com/amplitude/amplitude-js-gtm/pull/16/files

**Review by kevinpagtakhan — APPROVED** [review]

**Comment by kevinpagtakhan** [comment]
> > @yuhao900914 from @kevinpagtakhan comment yesterday, should we also update [this part](https://github.com/amplitude/Amplitude-TypeScript/blob/cbf268ffa158d450aab8e501b6ceefc29aa0ac4b/packages/marketing-analytics-browser/generated/amplitude-gtm-snippet.js#L91) to include the following?
> > ```
> > if (!window.amplitude) {
> >   window.amplitude = window.amplitudeGTM;
> > }
> > ```
> 
> @justin-fiedler Should this logic exist on amplitude-js-gtm side? https://github.com/amplitude/amplitude-js-gtm/pull/16/files
> 
> If we added the logic here, on the GTM side, we need to check both window.amplitude and window.amplitube again. Let me know if I thought something wrong. Thank you.

When we add the logic above, we need to make sure this assignment operation only happens when the SDK script (not just the snippet loader) is loaded and parsed by the browser already; otherwise `amplitude` my only contain snippet loader/proxy logic only

**Comment by justin-fiedler** [comment]
> > @yuhao900914 from @kevinpagtakhan comment yesterday, should we also update [this part](https://github.com/amplitude/Amplitude-TypeScript/blob/cbf268ffa158d450aab8e501b6ceefc29aa0ac4b/packages/marketing-analytics-browser/generated/amplitude-gtm-snippet.js#L91) to include the following?
> > ```
> > if (!window.amplitude) {
> >   window.amplitude = window.amplitudeGTM;
> > }
> > ```
> 
> @justin-fiedler Should this logic exist on amplitude-js-gtm side? https://github.com/amplitude/amplitude-js-gtm/pull/16/files
> 
> If we added the logic here, on the GTM side, we need to check both window.amplitude and window.amplitube again. Let me know if I thought something wrong. Thank you.

Ok, I'm good with it as-is.

**Review by justin-fiedler — APPROVED** [review]

**Review by justin-fiedler — APPROVED** [review]

**Pull request merged**
